/*
 * This file was autogenerated
 * DO NOT EDIT
 * (C) 2015-2019 Renesas Electronics Europe, LTD
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __RZN1_IRQ_H__
#define __RZN1_IRQ_H__

#ifndef CORE_CA7
    #error "CA7 Interrupt File selected for non-CA7 build target "
#endif

/* See section 9.2.4 (Interrupts Allocation and Vector Number )r01uh0750ej0016-rzn1-introduction_Preliminary.pdf */
#define RZN1_SGI_0                  0
#define RZN1_SGI_1                  1
#define RZN1_SGI_2                  2
#define RZN1_SGI_3                  3
#define RZN1_SGI_4                  4
#define RZN1_SGI_5                  5
#define RZN1_SGI_6                  6
#define RZN1_SGI_7                  7
#define RZN1_SGI_8                  8
#define RZN1_SGI_9                  9
#define RZN1_SGI_10                 10
#define RZN1_SGI_11                 11
#define RZN1_SGI_12                 12
#define RZN1_SGI_13                 13
#define RZN1_SGI_14                 14
/* Reserved for PPI interrupts      15-31*/

#define RZN1_IRQ_ADC                32
#define RZN1_IRQ_I2C0               33
#define RZN1_IRQ_I2C1               34
#define RZN1_IRQ_SAFETY_FILTERING   35
#define RZN1_IRQ_SGPIO0             36
#define RZN1_IRQ_SGPIO1             37
#define RZN1_IRQ_UART0              38
#define RZN1_IRQ_UART1              39
#define RZN1_IRQ_UART2              40
#define RZN1_IRQ_DELTASIGMA         41
#define RZN1_IRQ_PWMPTO             42
#define RZN1_IRQ_ECC_4MB            43
#define RZN1_IRQ_ECC_2MB            44
#define RZN1_IRQ_CM3_LOCKUP         45
#define RZN1_IRQ_CM3_TRING_0        46
#define RZN1_IRQ_CM3_TRING_1        47
#define RZN1_IRQ_HWRTOS_BRAMERR     48
#define RZN1_IRQ_HWRTOS_BUFDMA      49
#define RZN1_IRQ_HWRTOS_BUFDMAERR   50
#define RZN1_IRQ_HWRTOS_ETHMII      51
#define RZN1_IRQ_HWRTOS_ETHPAUSE    52
#define RZN1_IRQ_HWRTOS_ETHRXDERR   53
#define RZN1_IRQ_HWRTOS_ETHRXDMA    54
#define RZN1_IRQ_HWRTOS_ETHRXERR    55
#define RZN1_IRQ_HWRTOS_ETHRXFIFO   56
#define RZN1_IRQ_HWRTOS_ETHTX       57
#define RZN1_IRQ_HWRTOS_ETHTXDERR   58
#define RZN1_IRQ_HWRTOS_ETHTXDMA    59
#define RZN1_IRQ_HWRTOS_ETHTXFIFO   60
#define RZN1_IRQ_HWRTOS_ETHTXFIFOERR    61
#define RZN1_IRQ_HWRTOS                 62
#define RZN1_IRQ_HWRTOS_MACDMARXFRM     63
#define RZN1_IRQ_HWRTOS_TM_LPI_AST      64
#define RZN1_IRQ_HWRTOS_TM_LPI_DEAST    65
#define RZN1_IRQ_SBD0           66
#define RZN1_IRQ_LPI0           67
#define RZN1_IRQ_PMT0           68
#define RZN1_IRQ_SBD1           69
#define RZN1_IRQ_LPI1           70
#define RZN1_IRQ_PMT1           71
#define RZN1_IRQ_SWITCHDLR      72
/* RESERVED                     73 */
#define RZN1_IRQ_SWITCH         74
#define RZN1_IRQ_SWITCHPRP      75
#define RZN1_IRQ_ETHSWHUB       76
#define RZN1_IRQ_ETHSWPTRN      77
#define RZN1_IRQ_CAT_RST        78
#define RZN1_IRQ_CAT_SYNC_0     79
#define RZN1_IRQ_CAT_SYNC_1     80
#define RZN1_IRQ_CAT_WDT        81  /* shared */
#define RZN1_IRQ_S3_DIVCLK      81  /* shared */
#define RZN1_IRQ_CAT_EOF        82  /* shared */
#define RZN1_IRQ_S3_CONCLK      82  /* shared */
#define RZN1_IRQ_HSR_PTP        82  /* shared */
#define RZN1_IRQ_CAT_SOF        83  /* shared */
#define RZN1_IRQ_S3_0           83  /* shared */
#define RZN1_IRQ_HSR_CPU        83  /* shared */
#define RZN1_IRQ_CAT            84  /* shared */
#define RZN1_IRQ_S3_1           84  /* shared */
#define RZN1_IRQ_NOCFIREWALL    85
#define RZN1_IRQ_CRYPTO0        86
#define RZN1_IRQ_CRYPTO1        87
#define RZN1_IRQ_DMA0           88
#define RZN1_IRQ_DMA1           89
#define RZN1_IRQ_NAND           90
#define RZN1_IRQ_IPCM_0         91
#define RZN1_IRQ_IPCM_1         92
#define RZN1_IRQ_IPCM_2         93
#define RZN1_IRQ_MSEBIM         94
#define RZN1_IRQ_MSEBIS         95
#define RZN1_IRQ_QSPI0          96
#define RZN1_IRQ_QSPI1          97
#define RZN1_IRQ_RTCATINTAL     98
#define RZN1_IRQ_RTCATINTR      99
#define RZN1_IRQ_RTCATINT1S     100
#define RZN1_IRQ_SDIO0          101
#define RZN1_IRQ_SDIO0_WKUP     102
#define RZN1_IRQ_SDIO1          103
#define RZN1_IRQ_SDIO1_WKUP     104
#define RZN1_IRQ_WATCHDOG_RESETN_0      105
#define RZN1_IRQ_WATCHDOG_RESETN_1      106
#define RZN1_IRQ_WATCHDOG_CM3_RESETN    107
#define RZN1_IRQ_DDRSUB         108
#define RZN1_IRQ_USBF_EPC       109
#define RZN1_IRQ_USBF           110
#define RZN1_IRQ_USBH_BIND      111
#define RZN1_IRQ_SPI0           112
#define RZN1_IRQ_SPI1           113
#define RZN1_IRQ_SPI2           114
#define RZN1_IRQ_SPI3           115
#define RZN1_IRQ_SPI4           116
#define RZN1_IRQ_SPI5           117
#define RZN1_IRQ_UART3          118
#define RZN1_IRQ_UART4          119
#define RZN1_IRQ_UART5          120
#define RZN1_IRQ_UART6          121
#define RZN1_IRQ_UART7          122
#define RZN1_IRQ_SGPIO2         123
#define RZN1_IRQ_SGPIO3         124
#define RZN1_IRQ_SGPIO4         125
#define RZN1_IRQ_RSV            126
#define RZN1_IRQ_CAN0           127
#define RZN1_IRQ_CAN1           128
#define RZN1_IRQ_LCD            129
/* RESERVED                     130 */
/* RESERVED                     131 */
#define RZN1_IRQ_WATCHDOGSAFE0  132
#define RZN1_IRQ_WATCHDOGSAFE1  133
#define RZN1_IRQ_RESET          134
#define RZN1_IRQ_GPIO_0         135
#define RZN1_IRQ_GPIO_1         136
#define RZN1_IRQ_GPIO_2         137
#define RZN1_IRQ_GPIO_3         138
#define RZN1_IRQ_GPIO_4         139
#define RZN1_IRQ_GPIO_5         140
#define RZN1_IRQ_GPIO_6         141
#define RZN1_IRQ_GPIO_7         142
/* RESERVED                     143 */
#define RZN1_IRQ_TIMER0_0       144
#define RZN1_IRQ_TIMER0_1       145
#define RZN1_IRQ_TIMER0_2       146
#define RZN1_IRQ_TIMER0_3       147
#define RZN1_IRQ_TIMER0_4       148
#define RZN1_IRQ_TIMER0_5       149
#define RZN1_IRQ_TIMER0_6       150
#define RZN1_IRQ_TIMER0_7       151
#define RZN1_IRQ_TIMER1_0       152
#define RZN1_IRQ_TIMER1_1       153
#define RZN1_IRQ_TIMER1_2       154
#define RZN1_IRQ_TIMER1_3       155
#define RZN1_IRQ_TIMER1_4       156
#define RZN1_IRQ_TIMER1_5       157
#define RZN1_IRQ_TIMER1_6       158
#define RZN1_IRQ_TIMER1_7       159
#define RZN1_IRQ_NAXIERRIRQ     187
#define RZN1_IRQ_NCTIIRQ_0      188
#define RZN1_IRQ_NCTIIRQ_1      189
#define RZN1_IRQ_NPMUIRQ_0      190
#define RZN1_IRQ_NPMUIRQ_1      191

#define RZN1_INT_SRC_TOTAL  191

static __INLINE uint32_t ValidateIRQ(IRQn_Type IRQn)
{
    uint32_t retval;
    switch (IRQn)
    {
        /* Add to this list when interrupts are supported in a module */
        case (RZN1_SGI_0):
        case (RZN1_SGI_1):
        case (RZN1_SGI_2):
        case (RZN1_SGI_3):
        case (RZN1_SGI_4):
        case (RZN1_SGI_5):
        case (RZN1_SGI_6):
        case (RZN1_SGI_7):
        case (RZN1_SGI_8):
        case (RZN1_SGI_9):
        case (RZN1_SGI_10):
        case (RZN1_SGI_11):
        case (RZN1_SGI_12):
        case (RZN1_SGI_13):
        case (RZN1_SGI_14):

        case (RZN1_IRQ_PWMPTO):
        case (RZN1_IRQ_ADC):
        case (RZN1_IRQ_I2C0):
        case (RZN1_IRQ_I2C1):
        case (RZN1_IRQ_UART0):
        case (RZN1_IRQ_UART1):
        case (RZN1_IRQ_UART2):
        case (RZN1_IRQ_WATCHDOG_CM3_RESETN):
        case (RZN1_IRQ_WATCHDOG_RESETN_0):
        case (RZN1_IRQ_WATCHDOG_RESETN_1):
        case (RZN1_IRQ_USBF_EPC):
        case (RZN1_IRQ_USBF):
        case (RZN1_IRQ_USBH_BIND):
        case (RZN1_IRQ_MSEBIS):
        case (RZN1_IRQ_SDIO0):
        case (RZN1_IRQ_SDIO0_WKUP):
        case (RZN1_IRQ_SDIO1):
        case (RZN1_IRQ_SDIO1_WKUP):
        case (RZN1_IRQ_SPI0):
        case (RZN1_IRQ_SPI1):
        case (RZN1_IRQ_SPI2):
        case (RZN1_IRQ_SPI3):
        case (RZN1_IRQ_SPI4):
        case (RZN1_IRQ_SPI5):
        case (RZN1_IRQ_SBD0):
        case (RZN1_IRQ_LPI0):
        case (RZN1_IRQ_PMT0):
        case (RZN1_IRQ_SBD1):
        case (RZN1_IRQ_LPI1):
        case (RZN1_IRQ_PMT1):
        case (RZN1_IRQ_UART3):
        case (RZN1_IRQ_UART4):
        case (RZN1_IRQ_UART5):
        case (RZN1_IRQ_UART6):
        case (RZN1_IRQ_UART7):
        case (RZN1_IRQ_DMA0):
        case (RZN1_IRQ_DMA1):
        case (RZN1_IRQ_RTCATINTAL):
        case (RZN1_IRQ_RTCATINTR):
        case (RZN1_IRQ_RTCATINT1S):
        case (RZN1_IRQ_GPIO_0):
        case (RZN1_IRQ_GPIO_1):
        case (RZN1_IRQ_GPIO_2):
        case (RZN1_IRQ_GPIO_3):
        case (RZN1_IRQ_GPIO_4):
        case (RZN1_IRQ_GPIO_5):
        case (RZN1_IRQ_GPIO_6):
        case (RZN1_IRQ_GPIO_7):
        case (RZN1_IRQ_CAN0):
        case (RZN1_IRQ_CAN1):
        case (RZN1_IRQ_TIMER0_0):
        case (RZN1_IRQ_TIMER0_1):
        case (RZN1_IRQ_TIMER0_2):
        case (RZN1_IRQ_TIMER0_6):
        case (RZN1_IRQ_TIMER0_7):
        case (RZN1_IRQ_LCD):

            retval = true;
            break;

        default:
            retval = false;
            break;
    }

    return retval;
}
#endif /* __RZN1_IRQ_H__ */
