pl320 : pl320.c pl320.h shm.c shm.h 
	~/rzn_dev_setup/rzn1_linux-4.19_bsp/output/buildroot-2019.02.6/output/host/bin/arm-linux-gnueabihf-gcc  pl320.c shm.c -o pl320 -lpthread

clean : 
	rm pl320 pl320_rx
